BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input
            multiline: False

        Button:
            id: square_button
            text: 'Square'
            on_press: app.handle_calculate(int(input.text))

        Label:
            id: output
            color: (1, 1, 0, 0)

    Label:
        text: 'Enter a number and press "Square"'