BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input
            multiline: False
            text: '4.0'

        Button:
            id: square_button
            text: 'Square'
            on_press: app.handle_calculate(float(input.text))

        Label:
            id: output
            color: (1, 0.5, 0.7, 1)

    Label:
        text: 'Enter a number and press "Square"'